version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "5055:5055"
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped